# Generate ChessgroundUnstyled.svelte from Chessground.svelte

use 5.30.0;
use warnings;

sub read_text {
	my ($path) = @_;
	open my $fh, '<', $path or die "Failed to read $path: $!";
	local $/;
	return <$fh>;
}

sub write_text {
	my ( $path, $contents ) = @_;
	open my $fh, '>', $path or die "Failed to write $path: $!";
	print {$fh} $contents or die "Failed to write $path: $!";
	return 1;
}

my $unstyled = read_text( 'src/lib/Chessground.svelte' );

# remove entire <style> except for a .cg-wrap{...} at the beginning
$unstyled =~ s@<style>(\s*\.cg-wrap\s+\{.*?\}).*</style>@<style>$1\n</style>@s;

# add file-is-generated comment
$unstyled =~ s@(<script>)@$1\n\t// This file was generated by generate_unstyled.pl\n\t@;

write_text( 'src/lib/ChessgroundUnstyled.svelte', $unstyled );
